1. Import the numpy package under the name np (★☆☆)

In [2]:
import numpy as np

2. Print the numpy version and the configuration

In [4]:
print(np.__version__)
np.show_config()

1.23.4
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

3. Create a null vector of size 10

In [5]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array

In [11]:
arr=np.zeros((5,5))
ans=arr.size*arr.itemsize
print(f"{ans} bytes")

200 bytes


5. How to get the documentation of the numpy add function from the command line? 

In [ ]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

6. Create a null vector of size 10 but the fifth value which is 1 

In [13]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49

In [14]:
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last)

In [15]:
arr=np.array([1,2,3,4,5,6])
print(arr[::-1])

[6 5 4 3 2 1]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
arr=np.arange(0,9)
narr=np.reshape(arr,(3,3))
print(narr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [19]:
arr=np.nonzero([1,2,0,0,4,0])
print(arr)

(array([0, 1, 4], dtype=int64),)


11. Create a 3x3 identity matrix 


In [20]:
arr=np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values 

In [22]:
arr=np.random.random((3,3,3))
print(arr)

[[[0.8674458  0.21401864 0.15859323]
  [0.80475553 0.46677616 0.79507089]
  [0.97196236 0.76237257 0.18517609]]

 [[0.61270132 0.45093774 0.86436907]
  [0.44987244 0.34781245 0.61081534]
  [0.11471392 0.99126236 0.89382054]]

 [[0.86902948 0.00826512 0.3369918 ]
  [0.94227516 0.52282249 0.57478023]
  [0.19729066 0.3956933  0.35319469]]]


13. Create a 10x10 array with random values and find the minimum and maximum values 

In [23]:
arr=np.random.random((10,10))
arr_min=arr.min()
arr_max=arr.max()
print(arr_min,arr_max)

0.0023661013078467574 0.9687987700159941


14. Create a random vector of size 30 and find the mean value

In [26]:
arr=np.random.random(30)
ans=arr.mean()
print(ans)

0.5851015403101325


15. Create a 2d array with 1 on the border and 0 inside

In [28]:
arr=np.ones((5,5))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array? 

In [29]:
arr=np.ones((5,5))
narr=np.pad(arr,pad_width=1,mode="constant",constant_values=0)
print(narr)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17. What is the result of the following expression? 

In [31]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [54]:
arr = np.diag((1,2,3,4))
arr = np.pad(arr,pad_width = ((1,0),(0,1)),mode = 'constant')
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern 

In [44]:
arr=np.ones((8,8))
arr[1::2,::2]=0
arr[::2,1::2]=0
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [45]:
res=np.unravel_index(100,(6,7,8))
print(res)

(1, 5, 4)


21. Create a checkerboard 8x8 matrix using the tile function 

In [50]:
arr=np.array([[1,0],[0,1]])
narr=np.tile(arr,(4,4))
print(narr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


22. Normalize a 5x5 random matrix

In [51]:
arr=np.random.random((5,5))
ans=(arr-np.mean(arr))/(np.std(arr))
print(ans)

[[-0.97119891  0.75779033  1.23493535 -1.17091573  0.14520384]
 [-0.33382087  1.41775579 -1.75771093  1.09268992 -0.95864076]
 [-0.40462004  0.09865385  0.04164684 -0.39857911  0.88273245]
 [-0.91109729  0.91587425 -1.48706305 -0.56556398  1.37711541]
 [ 1.53636916 -0.38512112 -1.53193507  0.34868854  1.02681111]]


Create a custom dtype that describes a color as four unsigned bytes (RGBA) 

In [59]:
arr=np.dtype([("R",np.uint8),("G",np.uint8),("B",np.uint8),("A",np.uint8)])
narr=np.array((1,1,1,1),dtype=arr)
print(narr['R'])
print(type(narr))

1
<class 'numpy.ndarray'>


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [69]:
arr1=np.random.random((5,3))
arr2=np.random.random((3,2))
ans=np.dot(arr1,arr2)
print(ans)
print(arr3 @ arr4)


[[0.67269238 1.08321745]
 [0.43453293 0.68315362]
 [0.74840244 0.77634186]
 [0.82978933 1.16395833]
 [1.01459152 1.23191455]]
[[1.0035076  0.56095164]
 [0.76131465 0.62857906]
 [1.48380443 0.71325796]
 [1.48862888 0.76535617]
 [1.51132089 0.81350055]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place. 

In [71]:
arr=np.arange(12)
arr[(arr>3)&(arr<8)]*=-1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11]


26. What is the output of the following script? 

In [72]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal? 

In [82]:
Z=np.arange(0,6)
print({Z**Z})
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

legel:[   1    1    4   27  256 3125]
[ 0  1  2  4  8 16]
[False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
[0. 1. 2. 3. 4. 5.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

28. What are the result of the following expressions?

In [85]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-2.14748365e+09]


C:\Users\Neheil\AppData\Local\Temp\ipykernel_10296\1422587819.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Neheil\AppData\Local\Temp\ipykernel_10296\1422587819.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


29. How to round away from zero a float array ?

In [87]:
arr=np.random.random((5,5))
narr=np.round(arr,3)
print(narr)


[[0.503 0.269 0.351 0.777 0.308]
 [0.956 0.314 0.366 0.097 0.635]
 [0.375 0.418 0.967 0.283 0.929]
 [0.432 0.328 0.58  0.272 0.861]
 [0.603 0.505 0.608 0.021 0.059]]


30. How to find common values between two arrays?

In [89]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([7,3,5,8,4,9])
ans=np.intersect1d(arr1,arr2)
print(ans)


[3 4 5]


31. How to ignore all numpy warnings (not recommended)?

In [92]:
d=np.seterr(all="ignore")
arr=np.ones(1)/0
_=np.seterr(**d)
#another way
with np.errstate(divide="ignore"):
    arr=np.ones(1)/0

32. Is the following expressions true?

In [94]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Neheil\AppData\Local\Temp\ipykernel_10296\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

33. How to get the dates of yesterday, today and tomorrow? 

In [98]:
today=np.datetime64("today","D")
print(f"Today:{today}")
yesterday=np.datetime64("today","D")-np.timedelta64(1,"D")
print(f"Yesterday:{yesterday}")
tomorrow=np.datetime64("today","D")+np.timedelta64(1,"D")
print(f"Tomorrow:{tomorrow}")

Today:2023-01-24
Yesterday:2023-01-23
Tomorrow:2023-01-25


34. How to get all the dates corresponding to the month of July 2016? 

In [99]:
arr=np.arange('2016-07','2016-08',dtype="datetime64[D]")
print(arr)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [101]:
A=np.ones(3)
B=np.ones(3)*2
np.add(A,B,out=B)
np.negative(A,out=A)
np.divide(A,2,out=A)
print(np.multiply(A,B,out=A))

[-1.5 -1.5 -1.5]


36. Extract the integer part of a random array using 5 different methods

In [113]:
arr=np.random.uniform(0,10,5)
print(arr)
print(arr-arr%1)
print(np.floor(arr))
print(np.ceil(arr)-1)
print(arr.astype(int))
print(np.trunc(arr))

[2.55638922 1.37507427 1.87907813 4.31540064 1.27654371]
[2. 1. 1. 4. 1.]
[2. 1. 1. 4. 1.]
[2. 1. 1. 4. 1.]
[2 1 1 4 1]
[2. 1. 1. 4. 1.]


37. Create a 5x5 matrix with row values ranging from 0 to 4

In [115]:
arr=np.zeros((5,5))
arr+=np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38. Consider a generator function that generates 10 integers and use it to build an array

In [120]:
def generate():
   for i in range(10):
        yield i
z=np.fromiter(generate(),dtype=float)  
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [124]:
arr=np.linspace(0,1,11,endpoint=False)[1:]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. Create a random vector of size 10 and sort it 

In [125]:
arr=np.random.random(10)
arr.sort()
print(arr)

[0.01415769 0.04552311 0.12002575 0.36729313 0.37154658 0.37399312
 0.45408445 0.49397872 0.50424858 0.60766823]


41. How to sum a small array faster than np.sum?

In [128]:
arr=np.arange(5)
np.add.reduce(arr)

10

42. Consider two random array A and B, check if they are equal

In [133]:
arr1=np.random.randint(0,2,5)
arr2=np.random.randint(0,2,5)
ans1=np.array_equal(arr1,arr2)
print(ans1)

False


43. Make an array immutable (read-only)

In [135]:
arr=np.arange(0,5)
arr.flags.writeable=False
arr[0]=1
print(arr)

ValueError: assignment destination is read-only

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates 

45. Create random vector of size 10 and replace the maximum value by 0

In [137]:
arr=np.random.random(10)
a=arr.argmax()
arr[a]=0
print(arr)

[0.56055173 0.15362486 0.         0.6534137  0.24267355 0.52320471
 0.20515137 0.34191345 0.26949187 0.89015234]


46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [138]:
x=np.array([1,2,3,4])
y=np.array([5,6,7])
x=x.reshape((-1,1))
d_mat=x-y
ans=0.1/d_mat
print(ans)

[[-0.025      -0.02       -0.01666667]
 [-0.03333333 -0.025      -0.02      ]
 [-0.05       -0.03333333 -0.025     ]
 [-0.1        -0.05       -0.03333333]]


48. Print the minimum and maximum representable value for each numpy scalar type

In [140]:
for i in[np.int8,np.int32,np.int64]:
     print(np.iinfo(i).min)
     print(np.iinfo(i).max)
for i in[np.float32,np.float64]:
     print(np.finfo(i).min)
     print(np.finfo(i).max)
     print(np.finfo(i).eps)   

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


49. How to print all the values of an array?

In [147]:
z=np.zeros((16,16))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


50. How to find the closest value (to a given scalar) in a vector?

In [156]:
arr=np.random.uniform(0,10,10)
scalar=3
arr1=np.abs(arr-5)
print(arr)
print(arr1)
ans=arr1.argmin()
print(arr[ans])

[3.79392941 9.27295606 7.76687453 4.43445757 9.38723406 3.80132487
 4.63692034 0.68401278 0.4672539  1.11933715]
[1.20607059 4.27295606 2.76687453 0.56554243 4.38723406 1.19867513
 0.36307966 4.31598722 4.5327461  3.88066285]
4.636920337486746


51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [157]:
arr=np.zeros(10,[("position",[("x",float),
                ("y",float)]),[("color",[("r",float),
                              ("g",float),("b",float)])])
print(z)

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' on line 1 (2064842730.py, line 3)

52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances 

53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [158]:
arr=np.arange(10,dtype=np.float32)
arr1=arr.astype(np.int32,copy=False)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


54. How to read the following file?

In [161]:
from io import StringIO
s=StringIO("""1, 2, 3, 4, 5
              6,  ,  , 7, 8
               ,  , 9,10,11""")
arr=np.genfromtxt(s,delimiter=",",dtype=np.int32)
print(arr)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


55. What is the equivalent of enumerate for numpy arrays?

In [167]:
arr=np.array([[1,2,3],[5,6,7]])
for index, i in np.ndenumerate(arr):
    print(index,i)
print("*********************************************")    
arr1=np.arange(9).reshape(3,3)
for index in np.ndindex(arr1.shape):
    print(index)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 5
(1, 1) 6
(1, 2) 7
*********************************************
(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 1)
(1, 2)
(2, 0)
(2, 1)
(2, 2)


56. Generate a generic 2D Gaussian-like array

In [172]:
x,y=np.meshgrid(np.linspace(-1,1,5),np.linspace(-1,1,5))
D=np.sqrt(x**2+y**2)
sigma,mu=1.0,0.0
G=np.exp(-((D-mu)**2/(2.0*sigma**2)))
print(G)

[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


57. How to randomly place p elements in a 2D array?

In [182]:
p=3
Z = np.zeros((5,5))
np.put(Z, np.random.choice(range(5*5), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]


58. Subtract the mean of each row of a matrix

In [188]:
arr=np.random.rand(5,5)
arr1=arr-arr.mean(axis=1,keepdims=True)
print(arr1)

[[-0.15499949 -0.03893043 -0.0301082   0.44774631 -0.2237082 ]
 [-0.14577961 -0.02726104  0.01522889  0.1481339   0.00967787]
 [ 0.12076577  0.09784953 -0.04233226  0.10138391 -0.27766694]
 [ 0.01116881  0.35113498 -0.14603672 -0.4618698   0.24560274]
 [ 0.12832777 -0.16888083  0.11068839  0.21491129 -0.28504663]]


59. How to sort an array by the nth column?

In [192]:
arr=np.random.randint(0,10,(3,3))
print(arr)
print(arr[arr[:,1].argsort()])

[[0 8 8]
 [8 6 7]
 [5 2 7]]
[[5 2 7]
 [8 6 7]
 [0 8 8]]


60. How to tell if a given 2D array has null columns?

In [195]:
arr=np.random.randint(0,5,(5,10))
ans=(~z.any(axis=0)).any()
print(arr)
print(ans)

[[1 2 1 1 1 4 3 1 2 3]
 [1 4 2 3 2 2 0 3 3 0]
 [3 0 0 1 0 1 1 4 0 3]
 [2 4 0 2 4 4 4 1 2 0]
 [0 4 3 2 1 4 4 3 1 1]]
True


61. Find the nearest value from a given value in an array

In [201]:
arr=np.random.uniform(0,1,10)
k=0.5
ans=arr.flat[np.abs(arr-k).argmin()]

print(ans)

0.47648288896832236


62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 

In [207]:
arr1=np.arange(3).reshape(3,1)
arr2=np.arange(3).reshape(1,3)
fun=np.nditer([arr1,arr2,None])
for x,y,z in fun:z[...]=arr1+arr2
print(fun.operand[2])

ValueError: could not broadcast input array from shape (3,3) into shape ()

65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [210]:
x = [1,2,3,4,5,6]
I = [2,4,9,3,4,2]
F = np.bincount(I,x)
print(F)

[0. 0. 7. 4. 7. 0. 0. 0. 0. 3.]


67. Considering a four dimensions array, how to get sum over the last two axis at once?

In [214]:
arr=np.random.randint(0,10,(3,4,3,4))
ans=arr.sum(axis=(-2,-1))
print(ans)

[[50 59 51 48]
 [58 42 45 50]
 [51 70 38 65]]


68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

In [216]:
D=np.random.uniform(0,1,100)
S=np.random.randint(0,10,100)
Dsum=np.bincount(S,weights=D)
Dcounts=np.bincount(S)
Dmean=Dsum/Dcounts
print(Dmean)

[0.39412681 0.55307207 0.52078772 0.57835858 0.58224953 0.48510562
 0.29973156 0.59751454 0.44013175 0.38263523]


69. How to get the diagonal of a dot product? 

In [217]:
arr1=np.random.uniform(0,1,(5,5))
arr2=np.random.uniform(0,1,(5,5))
ans=np.sum(arr1*arr2.T,axis=1)
print(ans)

[1.26586937 0.98894411 0.9225927  1.3623873  1.67552976]


70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [219]:
arr=np.array([4,5,6,3,5])
c=3
arr1=np.zeros(len(arr)+(len(arr)-1)*c)
arr1[::c+1]=arr
print(arr1)

[4. 0. 0. 0. 5. 0. 0. 0. 6. 0. 0. 0. 3. 0. 0. 0. 5.]


71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? 

In [225]:
arr1=np.ones((5,5,3))
arr2=2*np.ones((5,5))
ans=arr1*arr2[:,:,None]
print(ans)

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


72. How to swap two rows of an array?

In [227]:
arr=np.arange(16).reshape(4,4)
arr[[0,1]]=arr[[1,0]]
print(arr)

[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C?

In [229]:
arr=np.bincount([1,4,5,3,6,7,2])
arr1=np.repeat(np.arange(len(arr)),arr)
print(arr1)

[1 2 3 4 5 6 7]


77. How to negate a boolean, or to change the sign of a float inplace? 

In [234]:
arr=np.random.randint(0,2,100)
print(np.logical_not(arr,out=arr))
print("#"*100)
arr1=np.random.uniform(-1.0,1.0,25)
print(np.negative(arr1,out=arr1))

[0 0 1 1 0 1 1 1 0 0 0 0 1 1 0 0 1 1 0 1 0 0 0 0 1 0 0 1 1 1 0 0 1 1 0 1 0
 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1 0 0 1 1 0 0 1
 0 1 0 0 1 1 0 0 0 0 1 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0]
####################################################################################################
[ 0.34863077  0.85980578  0.69012432 -0.34069505 -0.04093232  0.54877676
  0.23172657 -0.95514872 -0.17978289  0.34776254  0.34775546 -0.35333349
 -0.30791056 -0.25444903  0.04917588 -0.36066605  0.55133101 -0.88375071
  0.41152243 -0.45544545  0.83251127  0.78819524  0.10017322  0.15752162
 -0.64996272]


84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

82. Compute a matrix rank